# Generated by Django 3.1.6 on 2021-04-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='golfer',
            options={'managed': True, 'verbose_name': 'Tournament Golfer', 'verbose_name_plural': 'Tournament Golfers'},
        ),
    ]
