# Generated by Django 3.1.6 on 2021-04-07 16:38

import csv
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0003_add_golfer_city'),
    ]

    def add_city_data (apps, schema_editor):
        filename = "golfersInput.csv"
        input_file = open(filename, 'r')

        file_lines = csv.reader(input_file)

        golfers = list(file_lines)

        for golfer in golfers:
            golfer[0].strip()
            golfer[1].strip()
            golfer[2].strip()

        input_file.close()

        Golfer = apps.get_model('golfer', 'Golfer')

        for name, bdate, city in golfers:
            golfer = Golfer.objects.get(golfer_name=name)
            golfer.golfer_city = city
            golfer.save()

    def remove_city_data(apps, schema_editor):
        Golfer = apps.get_model('golfer', 'Golfer')
        Golfer.objects.update(golfer_city='unknown')


    operations = [
        migrations.RunPython(add_city_data, reverse_code=remove_city_data)
    ]
